/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ppe4;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julie
 */
public class Screen extends javax.swing.JFrame {

    private final Connection dataBase;
    private final String name;
    
    private String dom;
    
    private String sc1;
    private String sc2;
    private String sc3;
    private String sc4;
    private String sc5;
    private String sc6;
    
    
    
    /**
     * Creates new form Screen
     */
    public Screen(Connection dataBase, String name  ) {
        
        this.dataBase = dataBase;
        
        this.name = name ;
        initComponents();
        
        
        this.jLabel2.setText("Session : " +name);
        
        this.jButton13.setVisible(false);
        this.jButton14.setVisible(false);
        this.jButton15.setVisible(false);
        this.jButton16.setVisible(false);
        this.jButton17.setVisible(false);
        this.jButton18.setVisible(false);
        
        
        
        this.Tableau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                
                
                
            },
            new String [] {
                "Nom", "Précision", "Commentaire", "Référence","Quantité","Divers"
            }
        ));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tableau = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jButton5.setBackground(new java.awt.Color(204, 0, 51));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Alerte");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Session : NomUser");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/qzd.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/unnamed.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(293, 293, 293))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel3)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        jTextPane1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(204, 102, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Recherche");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 102, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Recherche Avancée");
        jButton2.setBorder(null);

        jButton3.setBackground(new java.awt.Color(204, 102, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Gestion du Matériel");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 102, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Liste du Matériel");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        Tableau.setBackground(new java.awt.Color(204, 204, 204));
        Tableau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tableau.setGridColor(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(Tableau);

        jButton7.setBackground(new java.awt.Color(0, 102, 51));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Appareillage");
        jButton7.setBorder(null);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 102, 51));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Media");
        jButton8.setBorder(null);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 102, 51));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Materiel de Laboratoire");
        jButton9.setBorder(null);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(0, 102, 51));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Electricité");
        jButton10.setBorder(null);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(0, 102, 51));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Produit Chimique");
        jButton11.setBorder(null);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(0, 102, 51));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Verreries et Associes");
        jButton12.setBorder(null);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(255, 153, 102));
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Observation");
        jButton13.setActionCommand("sc1");
        jButton13.setBorder(null);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(255, 153, 102));
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("jButton14");
        jButton14.setBorder(null);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(255, 153, 102));
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("jButton15");
        jButton15.setBorder(null);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(255, 153, 102));
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("jButton16");
        jButton16.setBorder(null);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(255, 153, 102));
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("jButton17");
        jButton17.setBorder(null);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(255, 153, 102));
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("jButton18");
        jButton18.setBorder(null);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 29, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        this.dom = "appareillage";
        
        
        this.jButton13.setVisible(rootPaneCheckingEnabled);
        jButton13.setText("Observation");
        this.sc1 = "observation";
        
        this.jButton14.setVisible(rootPaneCheckingEnabled);
        jButton14.setText("Mesures");
        this.sc2 = "mesures";
        
        this.jButton15.setVisible(rootPaneCheckingEnabled);
        jButton15.setText("ExAO");
        this.sc3 = "exao";
        
        this.jButton16.setVisible(rootPaneCheckingEnabled);
        jButton16.setText("Multimedia");
        this.sc4 = "multimedia";
        
        this.jButton17.setVisible(rootPaneCheckingEnabled);
        jButton17.setText("Experimentation");
        this.sc5 = "experimentation";
        
        this.jButton18.setVisible(rootPaneCheckingEnabled);
        jButton18.setText("Divers");
        this.sc6 = "divers";
        
        
             
            DefaultTableModel model = (DefaultTableModel)this.Tableau.getModel();
            model.setRowCount(0);

            ResultSet rs;

        try {
            rs = ConnectBDD.rqMeubleAppareillage(this.dataBase);
            
             while(rs.next()){ 
                 
                
                 
                 
                 
                int id = rs.getInt(1); 
                String nom = rs.getString(2); 
                String precision = rs.getString(3); 
                String commentaire = rs.getString(4);
                String reference = rs.getString(5);
                int quantite = rs.getInt(6);
                
              
                
                
                
                model.addRow(new Object[]{nom, precision,commentaire,reference, quantite});
             }


        
            
}       catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
      
 
            
            
            
            
                

        
        
        
        
        
        
        
             // TODO add your handling code here:
        
        
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        this.dom = "media";
        
        this.jButton13.setVisible(rootPaneCheckingEnabled);
        jButton13.setText("Logiciels");
        this.sc1 = "logiciels";
        
        this.jButton14.setVisible(rootPaneCheckingEnabled);
        jButton14.setText("DVD/VHS");
        this.sc2 = "dvdvhs";
        
        this.jButton15.setVisible(rootPaneCheckingEnabled);
        jButton15.setText("Manuels Scolaires");
        this.sc3 = "manuelsscolaires";
        
        this.jButton16.setVisible(rootPaneCheckingEnabled);
        jButton16.setText("Livre Scientifiques");
        this.sc4 = "livresscientifiques";
        
        this.jButton17.setVisible(rootPaneCheckingEnabled);
        jButton17.setText("Carte/Poster");
        this.sc5 = "carteposter";
        
        this.jButton18.setVisible(rootPaneCheckingEnabled);
        jButton18.setText("Divers");
        this.sc6 = "divers";
        
           
            DefaultTableModel model = (DefaultTableModel)this.Tableau.getModel();
            model.setRowCount(0);
            ResultSet rs;

        try {
            rs = ConnectBDD.rqMeubleMedia(this.dataBase);
            
             while(rs.next()){ 

                int id = rs.getInt(1); 
                String nom = rs.getString(2); 
                String precision = rs.getString(3); 
                String commentaire = rs.getString(4);
                String reference = rs.getString(5);
                int quantite = rs.getInt(6);
                
                model.addRow(new Object[]{nom, precision,commentaire,reference, quantite});
             }   
        }catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }                                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
        this.dom = "materieldelaboratoire";
        
        this.jButton13.setVisible(rootPaneCheckingEnabled);
        jButton13.setText("Appareils de Labo");
        this.sc1 = "appareilsdelabo";
        
        this.jButton14.setVisible(rootPaneCheckingEnabled);
        jButton14.setText("Sécurité");
        this.sc2 = "securite";
        
        this.jButton15.setVisible(rootPaneCheckingEnabled);
        jButton15.setText("Fournitures");
        this.sc3 = "fournitures";
        
        this.jButton16.setVisible(rootPaneCheckingEnabled);
        jButton16.setText("Mobilier ");
        this.sc4 = "mobilier";
        
        this.jButton17.setVisible(rootPaneCheckingEnabled);
        jButton17.setText("Divers");
        this.sc5 = "divers";
        
        this.jButton18.setVisible(false);

        
        
            DefaultTableModel model = (DefaultTableModel)this.Tableau.getModel();
            model.setRowCount(0);
            ResultSet rs;

        try {
            rs = ConnectBDD.rqMeubleeMaterielDeLaboratoire(this.dataBase);
            
             while(rs.next()){ 

                int id = rs.getInt(1); 
                String nom = rs.getString(2); 
                String precision = rs.getString(3); 
                String commentaire = rs.getString(4);
                String reference = rs.getString(5);
                int quantite = rs.getInt(6);
                
                model.addRow(new Object[]{nom, precision,commentaire,reference, quantite});
             }   
        }catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                        

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        this.dom = "electricite";
        
        this.jButton13.setVisible(rootPaneCheckingEnabled);
        jButton13.setText("Générateurs");
        this.sc1 = "generateurs";
        
        this.jButton14.setVisible(rootPaneCheckingEnabled);
        jButton14.setText("Mesures");
        this.sc2 = "mesures";
        
        this.jButton15.setVisible(rootPaneCheckingEnabled);
        jButton15.setText("Récepteurs");
        this.sc3 = "recepteurs";
        
        this.jButton16.setVisible(rootPaneCheckingEnabled);
        jButton16.setText("Connectique");
        this.sc4 = "connectique";
        
        this.jButton17.setVisible(rootPaneCheckingEnabled);
        jButton17.setText("Métaux");
        this.sc5 = "metaux";
        
        this.jButton18.setVisible(rootPaneCheckingEnabled);
        jButton18.setText("Divers");
        this.sc6 = "divers";
        
            DefaultTableModel model = (DefaultTableModel)this.Tableau.getModel();
            model.setRowCount(0);
            ResultSet rs;

        try {
            rs = ConnectBDD.rqMeubleeElectricite(this.dataBase);
            
             while(rs.next()){ 

                int id = rs.getInt(1); 
                String nom = rs.getString(2); 
                String precision = rs.getString(3); 
                String commentaire = rs.getString(4);
                String reference = rs.getString(5);
                int quantite = rs.getInt(6);
                
                model.addRow(new Object[]{nom, precision,commentaire,reference, quantite});
             }   
        }catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                         

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        this.dom = "produitchimique";
        
        this.jButton13.setVisible(rootPaneCheckingEnabled);
        jButton13.setText("Produits Organiques");
        this.sc1 = "produitsorganiques";
        
        this.jButton14.setVisible(rootPaneCheckingEnabled);
        jButton14.setText("Produits Minéraux");
        this.sc2 = "produitsmineraux";
        
        this.jButton15.setVisible(rootPaneCheckingEnabled);
        jButton15.setText("Enzymes");
        this.sc3 = "enzymes";
        
        this.jButton16.setVisible(rootPaneCheckingEnabled);
        jButton16.setText("Colorants");
        this.sc4 = "colorants";
        
        this.jButton17.setVisible(rootPaneCheckingEnabled);
        jButton17.setText("Entretien");
        this.sc5 = "entretien ";
        
        this.jButton18.setVisible(rootPaneCheckingEnabled);
        jButton18.setText("Autres");
        this.sc6 = "autres";
        
        
            DefaultTableModel model = (DefaultTableModel)this.Tableau.getModel();
            model.setRowCount(0);
            ResultSet rs;

        try {
            rs = ConnectBDD.rqMeubleeProduitChimique(this.dataBase);
            
             while(rs.next()){ 

                int id = rs.getInt(1); 
                String nom = rs.getString(2); 
                String precision = rs.getString(3); 
                String commentaire = rs.getString(4);
                String reference = rs.getString(5);
                int quantite = rs.getInt(6);
                
                model.addRow(new Object[]{nom, precision,commentaire,reference, quantite});
             }   
        }catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                         

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        this.dom = "verreriesetassocies";
        
        this.jButton13.setVisible(rootPaneCheckingEnabled);
        jButton13.setText("Verrerie");
        this.sc1 = "verrerie";
        
        this.jButton14.setVisible(rootPaneCheckingEnabled);
        jButton14.setText("Associés");
        this.sc2 = "associes";
        
        this.jButton15.setVisible(false);
       
        this.jButton16.setVisible(false);

        this.jButton17.setVisible(false);

        this.jButton18.setVisible(false);

        
        
        
            DefaultTableModel model = (DefaultTableModel)this.Tableau.getModel();
            model.setRowCount(0);
            ResultSet rs;

        try {
            rs = ConnectBDD.rqMeubleeVerreriesEtAssocies(this.dataBase);
            
             while(rs.next()){ 

                int id = rs.getInt(1); 
                String nom = rs.getString(2); 
                String precision = rs.getString(3); 
                String commentaire = rs.getString(4);
                String reference = rs.getString(5);
                int quantite = rs.getInt(6);
                
                model.addRow(new Object[]{nom, precision,commentaire,reference, quantite});
             }   
        }catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                         

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        

         DefaultTableModel model = (DefaultTableModel)this.Tableau.getModel();
            model.setRowCount(0);
            ResultSet rs;

        try {
            rs = ConnectBDD.rqMeubleeAppSc(this.dataBase, this.dom, this.sc1);
            
             while(rs.next()){ 

                int id = rs.getInt(1); 
                String nom = rs.getString(2); 
                String precision = rs.getString(3); 
                String commentaire = rs.getString(4);
                String reference = rs.getString(5);
                int quantite = rs.getInt(6);
                
                model.addRow(new Object[]{nom, precision,commentaire,reference, quantite});
             }   
        }catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
    }                                         

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:

        
        DefaultTableModel model = (DefaultTableModel)this.Tableau.getModel();
            model.setRowCount(0);
            ResultSet rs;

        try {
            rs = ConnectBDD.rqMeubleeAppSc(this.dataBase, this.dom, this.sc2);
            
             while(rs.next()){ 

                int id = rs.getInt(1); 
                String nom = rs.getString(2); 
                String precision = rs.getString(3); 
                String commentaire = rs.getString(4);
                String reference = rs.getString(5);
                int quantite = rs.getInt(6);
                
                model.addRow(new Object[]{nom, precision,commentaire,reference, quantite});
             }   
        }catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
    }                                         

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {                                          

        
        DefaultTableModel model = (DefaultTableModel)this.Tableau.getModel();
            model.setRowCount(0);
            ResultSet rs;

        try {
            rs = ConnectBDD.rqMeubleeAppSc(this.dataBase, this.dom, this.sc3);
            
             while(rs.next()){ 

                int id = rs.getInt(1); 
                String nom = rs.getString(2); 
                String precision = rs.getString(3); 
                String commentaire = rs.getString(4);
                String reference = rs.getString(5);
                int quantite = rs.getInt(6);
                
                model.addRow(new Object[]{nom, precision,commentaire,reference, quantite});
             }   
        }catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }                                         

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
           
        DefaultTableModel model = (DefaultTableModel)this.Tableau.getModel();
            model.setRowCount(0);
            ResultSet rs;

        try {
            rs = ConnectBDD.rqMeubleeAppSc(this.dataBase, this.dom, this.sc4);
            
             while(rs.next()){ 

                int id = rs.getInt(1); 
                String nom = rs.getString(2); 
                String precision = rs.getString(3); 
                String commentaire = rs.getString(4);
                String reference = rs.getString(5);
                int quantite = rs.getInt(6);
                
                model.addRow(new Object[]{nom, precision,commentaire,reference, quantite});
             }   
        }catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }                                         

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {                                          
          
        DefaultTableModel model = (DefaultTableModel)this.Tableau.getModel();
            model.setRowCount(0);
            ResultSet rs;

        try {
            rs = ConnectBDD.rqMeubleeAppSc(this.dataBase, this.dom, this.sc5);
            
             while(rs.next()){ 

                int id = rs.getInt(1); 
                String nom = rs.getString(2); 
                String precision = rs.getString(3); 
                String commentaire = rs.getString(4);
                String reference = rs.getString(5);
                int quantite = rs.getInt(6);
                
                model.addRow(new Object[]{nom, precision,commentaire,reference, quantite});
             }   
        }catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }                                         

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {                                          
           
        DefaultTableModel model = (DefaultTableModel)this.Tableau.getModel();
            model.setRowCount(0);
            ResultSet rs;

        try {
            rs = ConnectBDD.rqMeubleeAppSc(this.dataBase, this.dom, this.sc6);
            
             while(rs.next()){ 

                int id = rs.getInt(1); 
                String nom = rs.getString(2); 
                String precision = rs.getString(3); 
                String commentaire = rs.getString(4);
                String reference = rs.getString(5);
                int quantite = rs.getInt(6);
                
                model.addRow(new Object[]{nom, precision,commentaire,reference, quantite});
             }   
        }catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }                                         

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
         DefaultTableModel model = (DefaultTableModel)this.Tableau.getModel();
            model.setRowCount(0);
            ResultSet rs;

        try {
            rs = ConnectBDD.rqMeubleeAlerte(this.dataBase, this.dom, this.sc6);
            
             while(rs.next()){ 

                int id = rs.getInt(1); 
                String nom = rs.getString(2); 
                String precision = rs.getString(3); 
                String commentaire = rs.getString(4);
                String reference = rs.getString(5);
                int quantite = rs.getInt(6);
                
                model.addRow(new Object[]{nom, precision,commentaire,reference, quantite});
             }   
        }catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
        
        DefaultTableModel model = (DefaultTableModel)this.Tableau.getModel();
            model.setRowCount(0);
            ResultSet rs;

        try {
            rs = ConnectBDD.rqMeublee(this.dataBase, this.dom, this.sc6);
            
             while(rs.next()){ 

                int id = rs.getInt(1); 
                String nom = rs.getString(2); 
                String precision = rs.getString(3); 
                String commentaire = rs.getString(4);
                String reference = rs.getString(5);
                int quantite = rs.getInt(6);
                
                model.addRow(new Object[]{nom, precision,commentaire,reference, quantite});
             }   
        }catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
               DefaultTableModel model = (DefaultTableModel)this.Tableau.getModel();
            model.setRowCount(0);
            ResultSet rs;
            
            String recherchenom = this.jTextPane1.getText();
            

        try {
            rs = ConnectBDD.rqMeubleeName(this.dataBase, recherchenom );
            
             while(rs.next()){ 

                int id = rs.getInt(1); 
                String nom = rs.getString(2); 
                String precision = rs.getString(3); 
                String commentaire = rs.getString(4);
                String reference = rs.getString(5);
                int quantite = rs.getInt(6);
                
                model.addRow(new Object[]{nom, precision,commentaire,reference, quantite});
             }   
        }catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                        

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        
        Connexion con = new Connexion(this.dataBase);
        con.setVisible(true);
        this.dispose();
    }                                    

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    

    // Variables declaration - do not modify                     
    private javax.swing.JTable Tableau;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration                   
}
